function out_stuff = ImportPicarroFile(filename, dataLines)

%IMPORTFILE Import data from a text file
%  NOMAD20220625145946ZDATALOGUSERMINIMAL = IMPORTFILE(FILENAME) reads
%  data from text file FILENAME for the default selection.  Returns the
%  data as a table.
%
%  NOMAD20220625145946ZDATALOGUSERMINIMAL = IMPORTFILE(FILE, DATALINES)
%  reads data for the specified row interval(s) of text file FILENAME.
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  NOMAD20220625145946ZDataLogUserMinimal = importfile("C:\Users\thmorin\Documents\Projects\2022_ChristianBeaverProject\Data\Trip06242022\NOMAD-20220625-145946Z-DataLog_User_Minimal.dat", [1, Inf]);
%  See also READTABLE.
%
% Auto-generated by MATLAB on 05-Jul-2022 14:30:55

%% Input handling
% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end
%% Set up the Import Options and import the data
opts = fixedWidthImportOptions("NumVariables", 22);

% Specify range and variable widths
opts.DataLines = dataLines;
opts.VariableWidths = [10, 28, 34, 25, 21, 24, 25, 31, 26, 26, 26, 26, 26, 26, 27, 28, 23, 26, 26, 26, 26, 36];

% Specify column names and types
opts.VariableNames = ["DATE", "TIME", "FRAC_DAYS_SINCE_JAN1", "FRAC_HRS_SINCE_JAN1", "EPOCH_TIME", "ALARM_STATUS", "INST_STATUS", "CH4", "CH4_dry", "CO2", "CO2_dry", "H2O", "CavityPressure", "CavityTemp", "Battery_Current", "Battery_Temperature", "Battery_Voltage", "GPS_ABS_LAT", "GPS_ABS_LONG", "GPS_FIT", "GPS_TIME", "GPS_ALTITUDE"];
opts.VariableTypes = ["datetime", "datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "DATE", "InputFormat", "yyyy-MM-dd");
opts = setvaropts(opts, "TIME", "InputFormat", "HH:mm:ss.SSS");

% Import the data
out_stuff = readtable(filename, opts);

end