function fluxmetadata08182022 = ImportHWF_BeaverDamChambers(filename, dataLines)
%IMPORTFILE Import data from a text file
%  FLUXMETADATA06242022 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  FLUXMETADATA06242022 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  fluxmetadata06242022 = importfile("C:\Users\thmorin\Documents\Projects\2022_ChristianBeaverProject\Data\Trip06242022\flux_metadata_06242022.csv", [3, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 05-Jul-2022 14:12:44

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [3, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 14);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Date", "Name", "nb_start", "Start_Temp", "nb_end", "End_Temp", "start_time", "end_time", "elapsed", "Start_offset", "End_offset", "ChamberArea", "ChamberVolume","Shift_back", "data_sheet", "weather", "Notes","Var12", "Var13", "Var14"];
opts.SelectedVariableNames = ["Date", "Name", "nb_start", "Start_Temp", "nb_end", "End_Temp", "start_time", "end_time", "elapsed", "Start_offset", "End_offset", "ChamberArea", "ChamberVolume", "Shift_back", "data_sheet", "weather", "Notes"];
opts.VariableTypes = ["datetime", "char", "datetime", "double", "datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "char", "char", "char", "char", "char", "char"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Name", "data_sheet", "Var12", "Var13", "Var14"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Name", "data_sheet", "Var12", "Var13", "Var14"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Date", "InputFormat", "MM/dd/yyyy");
% opts = setvaropts(opts, "start_time", "InputFormat", "HH:mm:ss");
% opts = setvaropts(opts, "end_time", "InputFormat", "HH:mm:ss");

% Import the data
fluxmetadata08182022 = readtable(filename, opts);

end